import { Category, CategoryGroup, CategoryGroupDef } from '../types';

export const CATEGORY_GROUPS: CategoryGroupDef[] = [
  { id: 'streets', title: 'Streets & Pavements' },
  { id: 'environment', title: 'Environment' },
  { id: 'transport', title: 'Transport' },
  { id: 'safety', title: 'Safety & Crime' },
  { id: 'other', title: 'Other' },
];

export const CATEGORIES: Category[] = [
  // === STREETS ===
  {
    id: 'potholes',
    title: 'Potholes',
    subtitle: 'Road surface damage',
    icon: '🕳️',
    color: '#3A7BD5',
    group: 'streets',
    responsibleAuthority: 'auto',
    escalationDays: 10,
    extraFields: [
      { key: 'severity', label: 'Severity', type: 'options', options: ['Minor', 'Moderate', 'Severe'] },
    ],
  },
  {
    id: 'broken-paving',
    title: 'Broken Paving',
    subtitle: 'Damaged pavements',
    icon: '🧱',
    color: '#3A7BD5',
    group: 'streets',
    responsibleAuthority: 'auto',
    escalationDays: 10,
  },
  {
    id: 'streetlights',
    title: 'Streetlights',
    subtitle: 'Faulty lighting',
    icon: '💡',
    color: '#3A7BD5',
    group: 'streets',
    responsibleAuthority: 'auto',
    escalationDays: 5,
  },
  {
    id: 'road-markings',
    title: 'Road Markings',
    subtitle: 'Faded or missing markings',
    icon: '🛣️',
    color: '#FF6B35',
    group: 'streets',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 15,
  },

  // === ENVIRONMENT ===
  {
    id: 'fly-tipping',
    title: 'Fly-Tipping',
    subtitle: 'Illegal dumping',
    icon: '🗑️',
    color: '#2BAE66',
    group: 'environment',
    responsibleAuthority: 'auto',
    escalationDays: 5,
    extraFields: [
      { key: 'wasteType', label: 'Type of Waste', type: 'options', options: ['Household', 'Commercial', 'Construction', 'Other'] },
    ],
  },
  {
    id: 'graffiti',
    title: 'Graffiti',
    subtitle: 'Unwanted graffiti',
    icon: '🎨',
    color: '#2BAE66',
    group: 'environment',
    responsibleAuthority: 'auto',
    escalationDays: 15,
  },
  {
    id: 'overflowing-bins',
    title: 'Overflowing Bins',
    subtitle: 'Full or damaged bins',
    icon: '🗑️',
    color: '#2BAE66',
    group: 'environment',
    responsibleAuthority: 'auto',
    escalationDays: 3,
  },
  {
    id: 'parks-greenspaces',
    title: 'Parks & Green Spaces',
    subtitle: 'Damage or maintenance',
    icon: '🌳',
    color: '#2BAE66',
    group: 'environment',
    responsibleAuthority: 'auto',
    escalationDays: 15,
  },
  {
    id: 'flooding',
    title: 'Flooding',
    subtitle: 'Water & drainage',
    icon: '🌊',
    color: '#3A7BD5',
    group: 'environment',
    responsibleAuthority: 'thames-water',
    fixedAuthorityId: 'thames-water',
    escalationDays: 2,
    extraFields: [
      { key: 'floodType', label: 'Type of Flooding', type: 'options', options: ['Surface water', 'Sewage'] },
    ],
  },

  // === TRANSPORT ===
  {
    id: 'traffic-lights',
    title: 'Traffic Lights',
    subtitle: 'Broken or malfunctioning',
    icon: '🚦',
    color: '#FF6B35',
    group: 'transport',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 2,
  },
  {
    id: 'bus-stops',
    title: 'Bus Stops',
    subtitle: 'Damaged shelters or signs',
    icon: '🚏',
    color: '#FF6B35',
    group: 'transport',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 10,
  },
  {
    id: 'tube-issues',
    title: 'Tube Issues',
    subtitle: 'Station or service problems',
    icon: '🚇',
    color: '#FF6B35',
    group: 'transport',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 5,
  },
  {
    id: 'bus-lanes',
    title: 'Bus Lanes',
    subtitle: 'Obstructions or damage',
    icon: '🚌',
    color: '#FF6B35',
    group: 'transport',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 10,
  },
  {
    id: 'cycle-lanes',
    title: 'Cycle Lanes',
    subtitle: 'Damage or obstructions',
    icon: '🚲',
    color: '#FF6B35',
    group: 'transport',
    responsibleAuthority: 'tfl',
    fixedAuthorityId: 'tfl',
    escalationDays: 10,
  },
  {
    id: 'obstructing-scooter',
    title: 'Obstructing Scooter',
    subtitle: 'Badly parked e-scooter/bike',
    icon: '🛴',
    color: '#00D166',
    group: 'transport',
    responsibleAuthority: 'lime',
    fixedAuthorityId: 'lime',
    escalationDays: 1,
  },
  {
    id: 'damaged-bike',
    title: 'Damaged Hire Bike',
    subtitle: 'Broken docked/dockless bike',
    icon: '🚲',
    color: '#00D166',
    group: 'transport',
    responsibleAuthority: 'lime',
    fixedAuthorityId: 'lime',
    escalationDays: 3,
  },

  // === SAFETY ===
  {
    id: 'crime',
    title: 'Report Crime',
    subtitle: 'Non-emergency crime report',
    icon: '🚨',
    color: '#E53E3E',
    group: 'safety',
    responsibleAuthority: 'met-police',
    fixedAuthorityId: 'met-police',
    escalationDays: 14,
  },
  {
    id: 'suspicious-activity',
    title: 'Suspicious Activity',
    subtitle: 'Report concerns',
    icon: '👁️',
    color: '#E53E3E',
    group: 'safety',
    responsibleAuthority: 'met-police',
    fixedAuthorityId: 'met-police',
    escalationDays: 14,
  },
  {
    id: 'asb',
    title: 'Anti-Social Behaviour',
    subtitle: 'Report ASB',
    icon: '⚠️',
    color: '#D4A017',
    group: 'safety',
    responsibleAuthority: 'auto',
    escalationDays: 10,
  },
  {
    id: 'noise',
    title: 'Noise',
    subtitle: 'Noise nuisance',
    icon: '🔊',
    color: '#D4A017',
    group: 'safety',
    responsibleAuthority: 'auto',
    escalationDays: 5,
    extraFields: [
      { key: 'frequency', label: 'Is this ongoing?', type: 'options', options: ['Happening now', 'Recurring', 'One-off'] },
    ],
  },

  // === OTHER ===
  {
    id: 'rough-sleeping',
    title: 'Rough Sleeping',
    subtitle: 'Alert outreach teams',
    icon: '🏠',
    color: '#E8734A',
    group: 'other',
    responsibleAuthority: 'streetlink',
    fixedAuthorityId: 'streetlink',
    escalationDays: 3,
    extraFields: [
      { key: 'timeSeen', label: 'Time Last Seen', type: 'options', options: ['Just now', 'Within 1hr', 'Over 1hr ago'] },
    ],
  },
  {
    id: 'abandoned-vehicle',
    title: 'Abandoned Vehicle',
    subtitle: 'Report vehicles',
    icon: '🚗',
    color: '#7F77DD',
    group: 'other',
    responsibleAuthority: 'auto',
    escalationDays: 14,
    extraFields: [
      { key: 'registration', label: 'Vehicle Registration', type: 'text', placeholder: 'e.g. AB12 CDE' },
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getCategoriesByGroup(group: CategoryGroup): Category[] {
  return CATEGORIES.filter((c) => c.group === group);
}
